{% set version = "11.0.0" %}

package:
  name: django-bootstrap3
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-bootstrap3/django-bootstrap3-{{ version }}.tar.gz
  sha256: 593f98c0b84e26ab61ef9d81d3f7c3691f1d8492c9343b03e9feb9e8e9404e6a

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - django >=1.8

test:
  commands:
    - python -c "import django; from django.conf import settings; settings.configure(INSTALLED_APPS=['bootstrap3']); django.setup(); import bootstrap3;"

about:
  home: https://github.com/dyve/django-bootstrap3
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Bootstrap 3 integration with Django.'
  description: |
    Write Django as usual, and let django-bootstrap3 make template output 
    into Bootstrap 3 code.
  doc_url: http://django-bootstrap3.readthedocs.org/
  dev_url: https://github.com/dyve/django-bootstrap3

extra:
  recipe-maintainers:
    - xmnlab
