travis:
  secure:
    BINSTAR_TOKEN: PvL1PDaw70pKSlY9vbyierxm48DZGiK9J2P7LS3V5E5/tKq6gnx1Pgt7HVNPcAk9sRHjfsgiH+aKIsxK0/OEhYFWS/KLc1rBp3wO3XWGqNT9HbF3ZZVkgf0rDOJNbd3zhcoQmnoyE3UAKGkIv/EIDKQtIc56P9D2ucACkxvnIi2lzaPhEb5kHhZgXfmVJR2g1SFoeiilW9u7on9mYpRK0XUMAOmaHDStyFRh/rG0/VZnmiPgmkjpL6GlfQyx+Q/6Re2Dv3d4noBfIwEc+b1PG9K/nNwX4f/oOlLO2yuyLFJ8lq0sA/L46bn2KaevpBZSRpPeLD5CNPQ9iIgCGq/K0XvFN5mOxGiwBVafRckfM8agjl04oTZ6Sv71jfczV14XbBU/bzLhotR7tLunW9iL3KDmyYccwsYVH8uBWes9Mwoevqdl4qHHfSMgv7KhPBL6WCPhTxaOP+4q51ylERejtyhuW3B8aTHyS4NmtWL00n/mpKMwJY9Tk6cBkmz5S7a4TRK7oUSPy7QGpZcYe0dHZ1FJg9cMLTvKeRfSEmwQiwP9poIgAjr2DCTqj3ha0zmiEGLUrwjtQAhGrVowy0JhXF9q+AI09U2wbgYobZXpricoeqCViL1eDEONgW+HxTWlrBm0GNOAnumZH1YxU6F+uh28wsX1/pxK9YXwuR0tUkw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
