travis:
  secure:
    BINSTAR_TOKEN: IZNYS7ohZ7Oil6HUo1fhvtD+gRfaiNCUowweZzIB/xqmdf2Xxjss4XHSa6Ql7ypXqFE6JOFlGzTlc9JctHaBjUJNlurgqBNOgmJWkT3QIzC8SRR1OKLOTHHicxS73jbAwh//MNdNk8BBcLxvGiRdC2LUuv594QVjz0o/4kXwLVEMN9wzkg3XgMWEyhyqKXpQe4z0SGne1+Bc8H+9e0MYSku+lEDRDOQ6XqBOIbbubinMNy+OPlUj5Wy+Lkv6cz/z6HnOT6FU9My2TH0Fiy/HM6qfENEgEK1xjQaIbyTMLRUUV6Q4Czryb7H/KEMCdcA3n9aKmxCMu4yNjuyfAamYslf1qcGFRd5b83FgGlf2Ql5VnLvSuIkJuBSWhKDH4l9WztHyg16i5Zna0/jv71Wv98JTVeG/hH+Coi/XWSboF00VWxjjqmBZAtXHTL4LoU7bbPFilchEkI23gc0m37PVlzmPbAUNlTzisRIPlcvzpVqZkShRTgoAIwOmxnO4OTzGxQbNpCWhJ/m1PvLtBv7d0ydR4q/HsY3eLB6MQhply5lboV3z2yoVBubOEmFYlYE920aknnIKUsWFl3kshmRZxBENPXeHXx/huMWtbToBuWcx8R0XP6biyOUkY+EW611IbzuWhgcDHsYqF3h+rnkyzT2xyhfwIxFeE68wfPyfmSA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
